set linesize 150

select 
child_number
,sql_type_mismatch
,optimizer_mismatch
,outline_mismatch
,stats_row_mismatch
,literal_mismatch
,force_hard_parse
,explain_plan_cursor
,buffered_dml_mismatch
,pdml_env_mismatch
,inst_drtld_mismatch
,slave_qc_mismatch
,typecheck_mismatch
,auth_check_mismatch
,bind_mismatch
,describe_mismatch
,language_mismatch
,translation_mismatch
,bind_equiv_failure
,insuff_privs
,insuff_privs_rem
,remote_trans_mismatch
,logminer_session_mismatch
,incomp_ltrl_mismatch
,overlap_time_mismatch
,edition_mismatch
,mv_query_gen_mismatch
,user_bind_peek_mismatch
,typchk_dep_mismatch
,no_trigger_mismatch
,flashback_cursor
,anydata_transformation
,pddl_env_mismatch
,top_level_rpi_cursor
,different_long_length
,logical_standby_apply
,diff_call_durn
,bind_uacs_diff
,plsql_cmp_switchs_diff
,cursor_parts_mismatch
,stb_object_mismatch
,crossedition_trigger_mismatch
,pq_slave_mismatch
,top_level_ddl_mismatch
,multi_px_mismatch
,bind_peeked_pq_mismatch
,mv_rewrite_mismatch
,roll_invalid_mismatch
,optimizer_mode_mismatch
,px_mismatch
,mv_staleobj_mismatch
,flashback_table_mismatch
,litrep_comp_mismatch
,plsql_debug
,load_optimizer_stats
,acl_mismatch
,flashback_archive_mismatch
,lock_user_schema_failed
,remote_mapping_mismatch
,load_runtime_heap_failed
,hash_match_failed
,purged_cursor
,bind_length_upgradeable
,use_feedback_stats
from v$sql_shared_cursor
where sql_id = '&sql_id';
